FRUITS = ['apple',
          'apricot',
          'banana',
          'blueberry',
          'cherry',
          'durian',
          'feijoa',
          'fig',
          'grape',
          'grapefruit',
          'guava',
          'honeydew',
          'kiwi',
          'lemon',
          'lime',
          'longan',
          'lychee',
          'mandarin',
          'mango',
          'mangosteen',
          'nashi',
          'nectarine',
          'orange',
          'passionfruit',
          'pawpaw',
          'papaya',
          'peach',
          'pear',
          'persimmon',
          'pineapple',
          'plum',
          'pomegranate',
          'rambutan',
          'raspberry',
          'rhubarb',
          'rockmelon',
          'star fruit',
          'strawberry',
          'tamarillo',
          'tangelo',
          'watermelon']

VEGES = ['artichoke',
         'aubergine',
         'asparagus',
         'legumes',
         'alfalfa sprouts',
         'azuki beans',
         'bean sprouts',
         'black beans',
         'black-eyed peas',
         'borlotti bean',
         'broad beans',
         'chickpeas',
         'green beans',
         'kidney beans',
         'lentils',
         'lima beans',
         'mung beans',
         'navy beans',
         'peanuts',
         'pinto beans',
         'runner beans',
         'split peas',
         'soy beans',
         'peas',
         'mangetout',
         'broccoflower',
         'broccoli',
         'brussels sprouts',
         'cabbage',
         'kohlrabi',
         'Savoy cabbage',
         'red cabbage',
         'cauliflower',
         'celery',
         'endive',
         'fiddleheads',
         'frisee',
         'fennel',
         'greens',
         'bok choy',
         'chard',
         'collard greens',
         'kale',
         'mustard greens',
         'spinach',
         'herbs',
         'anise',
         'basil',
         'caraway',
         'coriander',
         'chamomile',
         'daikon',
         'fennel',
         'lavender',
         'lemongrass',
         'marjoram',
         'oregano',
         'parsley',
         'rosemary',
         'thyme',
         'lettuce',
         'arugula',
         'mushrooms',
         'nettles',
         'okra',
         'onions',
         'chives',
         'garlic',
         'leek',
         'onion',
         'shallot',
         'scallion',
         'peppers',
         'bell pepper',
         'chili pepper',
         'jalapeno',
         'habanero',
         'paprika',
         'tabasco pepper',
         'cayenne pepper',
         'radicchio',
         'rhubarb',
         'root vegetables',
         'beetroot',
         'mangel wurzel',
         'carrot',
         'celeriac',
         'corms',
         'eddoe',
         'konjac',
         'taro',
         'water chestnut',
         'ginger',
         'parsnip',
         'rutabaga',
         'radish',
         'wasabi',
         'horseradish',
         'white radish',
         'tubers',
         'jicama',
         'jerusalem artichoke',
         'potato',
         'sweet potato',
         'yam',
         'turnip',
         'spinach',
         'salsify',
         'skirret',
         'sweetcorn',
         'topinambur',
         'squash',
         'acorn squash',
         'bitter melon',
         'butternut squash',
         'banana squash',
         'Zucchini',
         'delicata',
         'gem squash',
         'hubbard squash',
         'marrow',
         'spaghetti squash',
         'tat soi',
         'tomato',
         'watercress',
         ]
